### ISSUE TITLE
Maybe use native javascript `Intl` object instead

### ISSUE THREAD

**Issue by renatodeleao** [Crowd9/numeral-light#12]
For some reason, I received a subscription notification to this package and realised that we only use two functions and both functions can be achieved with [native javascript these days](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) (which has locales in the browser):

```diff
- const locale = require('numeral-light/locales/en-US')
- const { intabbr, intcomma } = require('numeral-light')
+ function intabbr(number, locale) {
+   return Intl.NumberFormat(locale, {
+     notation: "compact",
+     maximumFractionDigits: 0
+   }).format(number)
+ }

+ function intcomma(number, locale, { maximumFractionDigits = 0 } = {}) {
+   return Intl.NumberFormat(locale, {
+     maximumFractionDigits
+   }).format(number)
+ }

console.assert('1K' === intabbr(1234, 'en-US'))
console.assert('1,234' === intcomma(1234, 'en-US'))
```

**Edit:** for perf — not sure if relevant — we can optionally `memoize` `new Intl.NumberFormat()` to reuse on similar arguments subsquent calls and avoid creating a new object every time (we do it manually for some [number helpers at the dashboard](https://github.com/Crowd9/Gleam/blob/4eeea7e0ea996a2c39428362d34bb07eeed26283/app/vue-dashboard/src/utils/number.js#L14-L35))

**Comment by nskazki** [comment]
Thank you! IE11 is dead - we should do it. Here's a task for myself https://linear.app/gleamio/issue/GLM-6550.

**Comment by nskazki** [comment]
Done ❤️ 

https://github.com/Crowd9/Gleam/pull/28316/commits/874731ca72c5ed07b952dfc16bb077ef9636aa49
https://github.com/Crowd9/Gleam/pull/28316/commits/a90432cdaebee70c679e711cba2c1ef5159da919
